from tkinter import *
import tkinter.messagebox as box


def Screen1():
    window = Tk()
    window.geometry('640x360')
    window.title('Titanic Survival Menu Interface')
    frame = Frame(window)
    listbox = Listbox(frame, width = 70)
    listbox.insert(1, '1:Create a profile to test its survival')
    listbox.insert(2, '2:Pick an existing profile to predict survival')
    listbox.insert(3, '3:View machine learning model\'s rating of features by importance to survival')
    listbox.insert(4, '4:View Train Data')
    listbox.insert(5, '5:View Test Data')
    listbox.insert(6, '6:Generate all test predictions')
    listbox.insert(7, '7:Quit')
    btn = Button(frame, text = 'Choose', command = None)
    btn.pack(side = RIGHT, padx = 5)
    listbox.pack(side = LEFT)
    frame.pack(padx = 30, pady = 30)
    window.mainloop()
def Screen2(var):
    var = str(var)
    string = 'Your Choice: '+var+'\n Proceed?'
    box.askyesno('Selection', string)
def Screen3(var):
    var = str(var)
    string = 'Probability of Survival:'+var
    box.showinfo('Prediction', string)
def Screen4():
    window = Tk()
    window.geometry('1120x630')
    window.title('Predicting Survival of External Profile')
    entry1 = Entry(window)
    entry2 = Entry(window)
    entry3 = Entry(window)
    entry4 = Entry(window)
    entry5 = Entry(window)
    entry6 = Entry(window)
    entry7 = Entry(window)
    mainlabel = Label(window, text = '''Welcome to Profile Creation.
         Here you will be able to create your own profile with attributes 
         to find the predicted probability of survival for the profile.''', font = 'Helvetica 13 bold')
    label1 = Label(window, text = 'Enter the subject\'s ticket class - (1 = 1st, 2 = 2nd, 3 = 3rd): ')
    label2 = Label(window, text = 'Enter the subject\'s sex - (m or f):')
    label3 = Label(window, text = 'Enter the subject\'s age - (0-100):')
    label4 = Label(window, text = 'Enter the subject\'s number of siblings and spouses abord - (0-15):')
    label5 = Label(window, text = 'Enter the subject\'s number of parents and children abord - (0-15):')
    label6 = Label(window, text = '''Enter the subject\'s passenger fare; in 1912,
    £100 would be worth over £11000 today
    (typical fares- for 1st class: £50+ , for 2nd class: £20-£50 , for 3rd class: £20 and below):''')
    label7 = Label(window, text = '''Enter the subject\'s port of boarding :
    C = Cherbourg, Q = Queenstown, S = Southampton: ''')
    gap1 = Label(window, text = '')
    gap2 = Label(window, text = '')
    gap3= Label(window, text = '')
    btn1 = Button(window,text = 'Check', command = None)
    btn2 = Button(window,text = 'Check', command = None)
    btn3 = Button(window,text = 'Check', command = None)
    btn4 = Button(window,text = 'Check', command = None)
    btn5 = Button(window,text = 'Check', command = None)
    btn6 = Button(window,text = 'Check', command = None)
    btn7 = Button(window,text = 'Check', command = None)
    btn8 = Button(window,text = 'Predict...', command = None)
    gap1.grid(row = 1, column = 2)
    gap2.grid(row = 2, column = 2)
    gap3.grid(row = 3, column = 2)
    mainlabel.grid(row = 4, column = 2)
    label1.grid(row = 5, column = 1)
    entry1.grid(row = 5, column = 2)
    btn1.grid(row = 5, column = 3)
    label2.grid(row = 6, column = 1)
    entry2.grid(row = 6, column = 2)
    btn2.grid(row = 6, column = 3)
    label3.grid(row = 7, column = 1)
    entry3.grid(row = 7, column = 2)
    btn3.grid(row = 7, column = 3)
    label4.grid(row = 8, column = 1)
    entry4.grid(row = 8, column = 2)
    btn4.grid(row = 8, column = 3)
    label5.grid(row = 9, column = 1)
    entry5.grid(row = 9, column = 2)
    btn5.grid(row = 9, column = 3)
    label6.grid(row = 10, column = 1)
    entry6.grid(row = 10, column = 2)
    btn6.grid(row = 10, column = 3)
    label7.grid(row = 11, column = 1)
    entry7.grid(row = 11, column = 2)
    btn7.grid(row = 11, column = 3)
    btn8.grid(row = 12, column = 2)
    window.mainloop()
def Screen5(var):
    window = Tk()
    window.geometry('640x360')
    window.title('Predicting survival of internal profile')
    label1 = Label(window, text = 'There are 418 profiles to select from. \n Please enter a number between 1 and 418:')
    entry1 = Entry(window)
    btn1 = Button(window, text = 'Predict', command = None)
    label2 = Label(window, text = 'You have chosen:', font = 'Helvetica 13 bold')
    label3 = Label(window, text = var)
    gap1 = Label(window, text = '')
    gap2 = Label(window, text = '')
    gap3= Label(window, text = '')
    label1.grid(row = 1, column = 1, padx = 20)
    entry1.grid(row = 1, column = 2, padx = 20)
    btn1.grid(row = 1, column = 3)
    gap1.grid(row = 2)
    gap2.grid(row = 3)
    gap3.grid(row = 4)
    label2.grid(row = 4, column = 1, pady = 20)
    label3.grid(row = 5, column = 1)
    window.mainloop()
def Screen6():
    window = Tk()
    window.geometry('960x540')
    window.title('Feature Importance')
    label1 = Label(window, text = 'Here you can view the  machine learning model\'s rating of features by importance to survival \n x-axis = importance(F-score), y-axis = features')
    graph = PhotoImage(file = 'graph.gif')
    label2 = Label(window, image = graph)
    btn1 = Button(window, text = 'Ok', command = None)
    label1.pack()
    label2.pack()
    btn1.pack()
    window.mainloop()
def Screen7():
    window = Tk()
    window.geometry('880x495')
    window.title('Train Data')
    label1 = Label(window, text = 'Display data here')
    btn1 = Button(window, text = 'Ok', command = None)
    label1.pack()
    btn1.pack(side= BOTTOM)
    window.mainloop()
def Screen8():
    window = Tk()
    window.geometry('880x495')
    window.title('Test Data')
    label1 = Label(window, text = 'Display data here')
    btn1 = Button(window, text = 'Ok', command = None)
    label1.pack()
    btn1.pack(side= BOTTOM)
    window.mainloop()
def Screen9():
    window = Tk()
    window.geometry('880x495')
    window.title('Test Predictions')
    label1 = Label(window, text = 'Display predictions here')
    btn1 = Button(window, text = 'Ok', command = None)
    label1.pack()
    btn1.pack(side= BOTTOM)
    window.mainloop()

Screen1()
Screen2('INSERT OPTION')
Screen3('INSERT PROBABILITY')
Screen4()
Screen5('INSERT PROFILE AND DATA HERE')
Screen6()
Screen7()
Screen8()
Screen9()

